const Menu = [
    {
    id : 1,
    image : "https://images.pexels.com/photos/6855089/pexels-photo-6855089.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name : "JODHPUR",
    category  : "जोधपुर",
    state : 'Rajasthan',
    desc : "Jodhpur is a city in the Thar Desert of the northwest Indian state of Rajasthan. Its 15th-century Mehrangarh Fort is a former palace thats now a museum"
},
{id : 2,
image : "https://upload.wikimedia.org/wikipedia/commons/4/41/East_facade_Hawa_Mahal_Jaipur_from_ground_level_%28July_2022%29_-_img_01.jpg",
name : "JAIPUR",
category  : "जयपुर ",
state : 'Rajasthan',
desc : "Jaipur is the capital of India’s Rajasthan state. It evokes the royal family that once ruled the region and that, in 1727, or “Pink City” for its trademark building color."
},
{id : 3,
    image : "https://i.pinimg.com/564x/d9/98/13/d99813b257b925facd80885878656f86.jpg",
    name : "KOTA",
    category  : "कोटा  ",
    state : 'Rajasthan',
    desc : "Kota is a city on the Chambal River in Rajasthan, northern India. Inside the Kota Garh, or City Palace, the Maharao Madho Singh Museum paintings and antique weapons."
    },
    {id : 4,
        image : "http://jawaicastleresort.com/wp-content/uploads/2019/07/pmy.jpg",
        name : "PALI",
        category  : "पाली   ",
        state : 'Rajasthan',
        desc : "Pali is a city and capital division in Rajasthan state of India. It is the administrative headquarters of Pali District.It is known as The Industrial City"
        },
    {id : 5,
        image : "https://static.the.akdn/53832/1644531346-akaa-2013-nagaur-fort-india01_1.jpg?w=1800&auto=format",
        name : "NAGAUR",
        category  : "नागौर  ",
        state : 'Rajasthan',
        desc : "Nagaur is a city and municipal council in Nagaur district of the state of Rajasthan in India. It is the administrative headquarters of Nagaur District.."
            },
    {id : 6,
        image : "https://img.traveltriangle.com/blog/wp-content/uploads/2017/09/cover-for-Places-To-Visit-In-Ajmer.jpg",
        name : "AJMER",
        category  : "अजमेर  ",
        state : 'Rajasthan',
        desc : "Ajmer is a city in the northern Indian state of Rajasthan. South of the city's artificial Ana Sagar Lake is Ajmer Sharif Dargah, the domed shrine of the Muslim Sufi saint Garib Nawaz. "
            },
    {id : 7,
        image : "https://www.hotelrawalkot.com/wp-content/uploads/2019/05/Rajasthan.jpg",
        name : "JAISALMER",
        category  : "जैसलमेर   ",
        state : 'Rajasthan',
        desc : "Jaisalmer Fort is situated in the city of Jaisalmer, in the Indian state of Rajasthan. It is believed the very few living forts in the world population still resides within the fort."
            },
    {id : 8,
        image : "https://pickyourtrail.com/blog/wp-content/uploads/2020/06/photo-1514007631454-28669d6cc960.jpeg",
        name : "BIKANER",
        category  : "बीकानेर   ",
        state : 'Rajasthan',
        desc : "Bikaner is a city in the north Indian state of Rajasthan, east of the border with Pakistan. It's surrounded by the Thar Desert.Nearby, the Karni Mata Temple is home to many rats "
            }, 
    {id : 9,
        image : "https://www.holidify.com/images/compressed/attractions/attr_1646.jpg",
        name : "BARMER",
        category  : "बाड़मेर   ",
        state : 'Rajasthan',
        desc : "Barmer is a city and municipal council in the Barmer district in the state of Rajasthan, India. It is the administrative headquarters of Barmer district. ."
            },
    {id : 10,
        image : "https://upload.wikimedia.org/wikipedia/commons/f/f4/Harshnath_Temple-Sikar-Rajasthan-DSC0011.jpg",
        name : "SIKAR",
        category  : "सीकर   ",
        state : 'Rajasthan',
        desc : "Sikar is a city and municipal council in the Sikar district of the state of Rajasthan in India. It is the administrative headquarters of the Sikar district"
            },
   {id : 11,
        image : "https://www.rajras.in/wp-content/uploads/2020/06/Tonk-district-of-Rajasthan.jpg",
        name : "TONK",
        category  : "टोंक    ",
        state : 'Rajasthan',
        desc : "Tonk is a city in the Indian state of Rajasthan. The city is situated 95 km by road south from Jaipur, . It is the administrative headquarters of Tonk District. "
            },     
    {id : 12,
        image : "https://ak.jogurucdn.com/media/image/p17/place-2014-10-21-14-bharatpur8668cf9d78c82f576378acf7aa767aa4.jpg",
        name : "BHARATPUR",
        category  : "सीकर   ",
        state : 'Rajasthan',
        desc : "Bharatpur is an Indian city in eastern Rajasthan. At its center is the 18th-century Lohagarh Fort, surrounded by a moat. Inside the fort is the Government Museum."
            } ,
    {id : 13,
        image : "https://images.thrillophilia.com/image/upload/s--wI2Z-W6c--/c_fill,h_600,q_auto,w_975/f_auto,fl_strip_profile/v1/images/photos/000/004/175/original/1571215682_udaipur.jpg.jpg?1571215682",
        name : "UDAIPUR",
        category  : "उदयपुर    ",
        state : 'Rajasthan',
        desc : "Udaipur, formerly the capital of the Mewar Kingdom, is a city in the western Indian state of Rajasthan. Founded by Maharana Udai Singh II in 1559, it’s set around a series ."
            } 
];
export default Menu;